id: IB5C2F4D9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T06:06:19+00:00'
last_modified: '2022-06-07T17:00:55.667790+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20471
  title: བསྡུས་གྲྭར་ཐོག་མར་འཇུག་བྱེད་སྐྱབས་ཁྲིད་དང་འབྲེལ་བའི་མན་ངག་གསེར་གྱི་ལྡེ་མིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    9C2D:
      image_group_id: I1PD28068
      title: ''
      total_pages: 326
      order: 1
      base_file: 9C2D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
