id: P003014
initial_creation_type: ocr
source_metadata:
  id: bdr:W20471
  title: བསྡུས་གྲྭར་ཐོག་མར་འཇུག་བྱེད་སྐྱབས་ཁྲིད་དང་འབྲེལ་བའི་མན་ངག་གསེར་གྱི་ལྡེ་མིག
  author: ''
  volumes:
    61bcf3ae23f34f3e9fab15ceb9cdd204:
      image_group_id: I1PD28068
      title: ''
      volume_number: 1
      total_pages: 326
      base_file: v001.txt
