id: P003014
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 10:34:24.511483
source_metadata:
  id: bdr:W20471
  title: བསྡུས་གྲྭར་ཐོག་མར་འཇུག་བྱེད་སྐྱབས་ཁྲིད་དང་འབྲེལ་བའི་མན་ངག་གསེར་གྱི་ལྡེ་མིག
  author: ''
  volumes:
    61bcf3ae23f34f3e9fab15ceb9cdd204:
      image_group_id: I1PD28068
      title: ''
      volume_number: 1
      total_pages: 326
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
